let res = {
  code: 200,
  message: "成功",
  content: [
    {
      level: 0,
      updateTime: 1672824651382,
      authorId: 4,
      title: "测试栏目",
      type: 0,
      content: "测试栏目",
      parentId: -1,
      createTime: 1672819888315,
      authorName: "user001",
      id: 96,
      state: 0,
      tag: "cslm",
    },
    {
      level: 0,
      modelId: 88,
      updateTime: 1672804711346,
      authorId: 4,
      title: "级联模拟",
      type: 1,
      content: "级联模拟",
      parentId: -1,
      modelName: "jlmn_jlmn",
      createTime: 1672804711346,
      authorName: "user001",
      id: 95,
      state: 0,
      tag: "jlmn",
    },
    {
      level: 0,
      columnList: [
        {
          level: 0,
          columnList: [
            {
              level: 0,
              updateTime: 1672997353885,
              authorId: 4,
              title: "dsvgds",
              type: 0,
              content: "sdfds",
              parentId: 75,
              createTime: 1672997353885,
              authorName: "user001",
              id: 121,
              state: 0,
              tag: "vrr",
            },
          ],
          updateTime: 1672733728174,
          authorId: 4,
          title: "3dtiles模型",
          type: 0,
          content: "3dtiles模型",
          parentId: 73,
          createTime: 1672733728174,
          authorName: "user001",
          id: 75,
          state: 0,
          tag: "c_3_3dtles",
        },
        {
          level: 0,
          columnList: [
            {
              level: 0,
              modelId: 86,
              updateTime: 1672734213832,
              authorId: 4,
              title: "其他",
              type: 1,
              content: "gltf模型，其他",
              parentId: 74,
              modelName: "qt_m_3_model",
              createTime: 1672734213832,
              authorName: "user001",
              id: 88,
              state: 0,
              tag: "qt",
            },
            {
              level: 0,
              modelId: 85,
              updateTime: 1672734194632,
              authorId: 4,
              title: "消防设备",
              type: 1,
              content: "gltf模型，消防设备",
              parentId: 74,
              modelName: "xfsb_m_3_model",
              createTime: 1672734194632,
              authorName: "user001",
              id: 87,
              state: 0,
              tag: "xfsb",
            },
            {
              level: 0,
              modelId: 84,
              updateTime: 1672734170268,
              authorId: 4,
              title: "植物",
              type: 1,
              content: "gltf模型，植物",
              parentId: 74,
              modelName: "zw_m_3_model",
              createTime: 1672734170268,
              authorName: "user001",
              id: 86,
              state: 0,
              tag: "zw",
            },
            {
              level: 0,
              modelId: 83,
              updateTime: 1672734145576,
              authorId: 4,
              title: "人物",
              type: 1,
              content: "gltf模型，人物",
              parentId: 74,
              modelName: "rw_m_3_model",
              createTime: 1672734145576,
              authorName: "user001",
              id: 85,
              state: 0,
              tag: "rw",
            },
            {
              level: 0,
              modelId: 82,
              updateTime: 1672734123096,
              authorId: 4,
              title: "街道及交通设施",
              type: 1,
              content: "gltf模型，街道及交通设施",
              parentId: 74,
              modelName: "jdjjtss_m_3_model",
              createTime: 1672734123096,
              authorName: "user001",
              id: 84,
              state: 0,
              tag: "jdjjtss",
            },
            {
              level: 0,
              modelId: 81,
              updateTime: 1672734086048,
              authorId: 4,
              title: "建筑物",
              type: 1,
              content: "gltf模型，建筑物",
              parentId: 74,
              modelName: "jzw_m_3_model",
              createTime: 1672734086048,
              authorName: "user001",
              id: 83,
              state: 0,
              tag: "jzw",
            },
            {
              level: 0,
              modelId: 80,
              updateTime: 1672734067437,
              authorId: 4,
              title: "火车及铁路",
              type: 1,
              content: "gltf模型，火车及铁路",
              parentId: 74,
              modelName: "hcjtl_m_3_model",
              createTime: 1672734067437,
              authorName: "user001",
              id: 82,
              state: 0,
              tag: "hcjtl",
            },
            {
              level: 0,
              modelId: 79,
              updateTime: 1672734039744,
              authorId: 4,
              title: "飞机及航空",
              type: 1,
              content: "gltf模型，飞机及航空",
              parentId: 74,
              modelName: "fjjhk_m_3_model",
              createTime: 1672734039744,
              authorName: "user001",
              id: 81,
              state: 0,
              tag: "fjjhk",
            },
            {
              level: 0,
              modelId: 78,
              updateTime: 1672734015665,
              authorId: 4,
              title: "电力设施",
              type: 1,
              content: "gltf模型，电力设施",
              parentId: 74,
              modelName: "dlss_m_3_model",
              createTime: 1672734015665,
              authorName: "user001",
              id: 80,
              state: 0,
              tag: "dlss",
            },
            {
              level: 0,
              modelId: 77,
              updateTime: 1672733994259,
              authorId: 4,
              title: "船舶及航海",
              type: 1,
              content: "gltf模型，船舶及航海",
              parentId: 74,
              modelName: "cbjhh_m_3_model",
              createTime: 1672733994259,
              authorName: "user001",
              id: 79,
              state: 0,
              tag: "cbjhh",
            },
            {
              level: 0,
              modelId: 76,
              updateTime: 1672733933065,
              authorId: 4,
              title: "车辆",
              type: 1,
              content: "gltf模型，车辆",
              parentId: 74,
              modelName: "cl_m_3_model",
              createTime: 1672733933065,
              authorName: "user001",
              id: 78,
              state: 0,
              tag: "cl",
            },
            {
              level: 0,
              modelId: 75,
              updateTime: 1672733909832,
              authorId: 4,
              title: "超高机械",
              type: 1,
              content: "gltf模型，超高机械",
              parentId: 74,
              modelName: "cgjx_m_3_model",
              createTime: 1672733909832,
              authorName: "user001",
              id: 77,
              state: 0,
              tag: "cgjx",
            },
            {
              level: 0,
              modelId: 74,
              updateTime: 1672733776781,
              authorId: 4,
              title: "测绘仪器",
              type: 1,
              content: "gltf模型，测绘仪器",
              parentId: 74,
              modelName: "chyq_m_3_model",
              createTime: 1672733776781,
              authorName: "user001",
              id: 76,
              state: 0,
              tag: "chyq",
            },
          ],
          updateTime: 1672733697033,
          authorId: 4,
          title: "gltf模型",
          type: 0,
          content: "gltf模型",
          parentId: 73,
          createTime: 1672733697033,
          authorName: "user001",
          id: 74,
          state: 0,
          tag: "c_gltf_model",
        },
      ],
      updateTime: 1672733655267,
      authorId: 4,
      title: "静态三维模型",
      type: 0,
      content: "静态三维模型库，gltf，3dtiles，水面",
      parentId: -1,
      createTime: 1672733655267,
      authorName: "user001",
      id: 73,
      state: 0,
      tag: "c_3_model",
    },
    {
      level: 0,
      modelId: 72,
      updateTime: 1672712777876,
      authorId: 4,
      title: "asdf",
      type: 1,
      content: "asdf",
      parentId: -1,
      modelName: "asdf_z_test",
      createTime: 1672712777876,
      authorName: "user001",
      id: 72,
      state: 0,
      tag: "asdf",
    },
    {
      level: 0,
      modelId: 53,
      updateTime: 1672298967154,
      authorId: 1,
      title: "我的模型",
      type: 1,
      content: "我的模型",
      parentId: -1,
      modelName: "pdsj_wdmx_my_model",
      createTime: 1672298967154,
      authorName: "super_user",
      id: 49,
      state: 0,
      tag: "pdsj_wdmx",
    },
    {
      level: 0,
      columnList: [
        {
          level: 0,
          columnList: [
            {
              level: 0,
              modelId: 65,
              updateTime: 1672303878622,
              authorId: 1,
              title: "垃圾堆放",
              type: 1,
              content: "垃圾堆放",
              parentId: 65,
              modelName: "ysljdf_tb_layer",
              createTime: 1672303878622,
              authorName: "super_user",
              id: 67,
              state: 0,
              tag: "ysljdf",
            },
          ],
          updateTime: 1672303526223,
          authorId: 1,
          title: "生态资源",
          type: 0,
          content: "生态资源",
          parentId: 20,
          createTime: 1672303526223,
          authorName: "super_user",
          id: 65,
          state: 0,
          tag: "shengtaizy",
        },
        {
          level: 0,
          columnList: [
            {
              level: 0,
              modelId: 66,
              updateTime: 1672304100934,
              authorId: 1,
              title: "林地非法侵占",
              type: 1,
              content: "林地非法侵占",
              parentId: 64,
              modelName: "ffqz_tb_layer",
              createTime: 1672304100934,
              authorName: "super_user",
              id: 68,
              state: 0,
              tag: "ffqz",
            },
          ],
          updateTime: 1672303505996,
          authorId: 1,
          title: "林地资源",
          type: 0,
          content: "林地资源",
          parentId: 20,
          createTime: 1672303505996,
          authorName: "super_user",
          id: 64,
          state: 0,
          tag: "linzy",
        },
        {
          level: 0,
          columnList: [
            {
              level: 0,
              modelId: 67,
              updateTime: 1672304392271,
              authorId: 1,
              title: "水域面积变化",
              type: 1,
              content: "水域面积变化",
              parentId: 22,
              modelName: "symjbh_tb_layer",
              createTime: 1672304392271,
              authorName: "super_user",
              id: 69,
              state: 0,
              tag: "symjbh",
            },
          ],
          updateTime: 1672215165197,
          authorId: 1,
          title: "水资源",
          type: 0,
          content: "水资源",
          parentId: 20,
          createTime: 1672215165197,
          authorName: "super_user",
          id: 22,
          state: 0,
          tag: "ysmx_szy",
        },
        {
          level: 0,
          columnList: [
            {
              level: 0,
              modelId: 64,
              updateTime: 1672303621288,
              authorId: 1,
              title: "永久基本农田监管",
              type: 1,
              content: "永久基本农田监管",
              parentId: 21,
              modelName: "yjjbntjg_tb_layer",
              createTime: 1672303621288,
              authorName: "super_user",
              id: 66,
              state: 0,
              tag: "yjjbntjg",
            },
          ],
          updateTime: 1672215150745,
          authorId: 1,
          title: "土地资源",
          type: 0,
          content: "土地资源",
          parentId: 20,
          createTime: 1672215150745,
          authorName: "super_user",
          id: 21,
          state: 0,
          tag: "ysmx_tdzy",
        },
      ],
      updateTime: 1672215114222,
      authorId: 1,
      title: "预设模型",
      type: 0,
      content: "预设模型",
      parentId: -1,
      createTime: 1672215114222,
      authorName: "super_user",
      id: 20,
      state: 0,
      tag: "pdsj_ysmx",
    },
    {
      level: 0,
      columnList: [
        {
          level: 0,
          columnList: [
            {
              level: 0,
              columnList: [
                {
                  level: 0,
                  modelId: 63,
                  updateTime: 1672303321965,
                  authorId: 1,
                  title: "垃圾堆放点",
                  type: 1,
                  content: "垃圾堆放点",
                  parentId: 62,
                  modelName: "lajidian_tb_layer",
                  createTime: 1672303321965,
                  authorName: "super_user",
                  id: 63,
                  state: 0,
                  tag: "lajidian",
                },
              ],
              updateTime: 1672303293746,
              authorId: 1,
              title: "生态资源",
              type: 0,
              content: "生态资源",
              parentId: 61,
              createTime: 1672303293746,
              authorName: "super_user",
              id: 62,
              state: 0,
              tag: "stzy",
            },
          ],
          updateTime: 1672303251759,
          authorId: 1,
          title: "周浦镇",
          type: 0,
          content: "周浦镇",
          parentId: 13,
          createTime: 1672303251759,
          authorName: "super_user",
          id: 61,
          state: 0,
          tag: "zhoupuzhen",
        },
        {
          level: 0,
          columnList: [
            {
              level: 0,
              updateTime: 1672215086928,
              authorId: 1,
              title: "水资源",
              type: 0,
              content: "水资源",
              parentId: 15,
              createTime: 1672215086928,
              authorName: "super_user",
              id: 19,
              state: 0,
              tag: "dtz_shuiziyuan",
            },
            {
              level: 0,
              columnList: [
                {
                  level: 0,
                  modelId: 45,
                  updateTime: 1672292875425,
                  authorId: 1,
                  title: "储备土地资源",
                  type: 1,
                  content: "储备土地资源",
                  parentId: 18,
                  modelName: "dtz_tudi_cbtdzy_cbtdz",
                  createTime: 1672292875425,
                  authorName: "super_user",
                  id: 43,
                  state: 0,
                  tag: "dtz_tudi_cbtdzy",
                },
                {
                  level: 0,
                  modelId: 44,
                  updateTime: 1672292822875,
                  authorId: 1,
                  title: "永久基本农田被占用",
                  type: 1,
                  content: "永久基本农田被占用",
                  parentId: 18,
                  modelName: "dtz_tudi_yjjbntbzy_yjjbntbzy",
                  createTime: 1672292822875,
                  authorName: "super_user",
                  id: 42,
                  state: 0,
                  tag: "dtz_tudi_yjjbntbzy",
                },
              ],
              updateTime: 1672215069958,
              authorId: 1,
              title: "土地资源",
              type: 0,
              content: "土地资源",
              parentId: 15,
              createTime: 1672215069958,
              authorName: "super_user",
              id: 18,
              state: 0,
              tag: "dtz_tudi",
            },
          ],
          updateTime: 1672214971778,
          authorId: 4,
          title: "大团镇",
          type: 0,
          content: "大团镇",
          parentId: 13,
          createTime: 1672214971778,
          authorName: "user001",
          id: 15,
          state: 0,
          tag: "datuanzhen",
        },
        {
          level: 0,
          columnList: [
            {
              level: 0,
              columnList: [
                {
                  level: 0,
                  modelId: 62,
                  updateTime: 1672302954045,
                  authorId: 1,
                  title: "公益林消涨",
                  type: 1,
                  content: "公益林消涨",
                  parentId: 53,
                  modelName: "gylxz_tb_layer",
                  createTime: 1672302954045,
                  authorName: "super_user",
                  id: 60,
                  state: 0,
                  tag: "gylxz",
                },
              ],
              updateTime: 1672302661335,
              authorId: 1,
              title: "林地资源",
              type: 0,
              content: "林地资源",
              parentId: 14,
              createTime: 1672302661335,
              authorName: "super_user",
              id: 53,
              state: 0,
              tag: "zhj-lin",
            },
            {
              level: 0,
              columnList: [
                {
                  level: 0,
                  modelId: 61,
                  updateTime: 1672302805766,
                  authorId: 1,
                  title: "垃圾堆放点",
                  type: 1,
                  content: "垃圾堆放点",
                  parentId: 52,
                  modelName: "ljdf_tb_layer",
                  createTime: 1672302805766,
                  authorName: "super_user",
                  id: 59,
                  state: 0,
                  tag: "ljdf",
                },
              ],
              updateTime: 1672302627709,
              authorId: 1,
              title: "生态资源",
              type: 0,
              content: "生态资源",
              parentId: 14,
              createTime: 1672302627709,
              authorName: "super_user",
              id: 52,
              state: 0,
              tag: "zhj-st",
            },
            {
              level: 0,
              columnList: [
                {
                  level: 0,
                  modelId: 41,
                  updateTime: 1672292291552,
                  authorId: 1,
                  title: "河道数据",
                  type: 1,
                  content: "河道数据",
                  parentId: 17,
                  modelName: "zjz_shui_hedao_hedao",
                  createTime: 1672292291552,
                  authorName: "super_user",
                  id: 39,
                  state: 0,
                  tag: "zjz_shui_hedao",
                },
                {
                  level: 0,
                  modelId: 40,
                  updateTime: 1672292202660,
                  authorId: 1,
                  title: "水域数据",
                  type: 1,
                  content: "水域数据",
                  parentId: 17,
                  modelName: "zjz_shui_shuiyu_shuiyu",
                  createTime: 1672292202660,
                  authorName: "super_user",
                  id: 38,
                  state: 0,
                  tag: "zjz_shui_shuiyu",
                },
              ],
              updateTime: 1672215049631,
              authorId: 1,
              title: "水资源",
              type: 0,
              content: "水资源",
              parentId: 14,
              createTime: 1672215049631,
              authorName: "super_user",
              id: 17,
              state: 0,
              tag: "zjz_shuiziyuan",
            },
            {
              level: 0,
              columnList: [
                {
                  level: 0,
                  modelId: 55,
                  updateTime: 1672302349164,
                  authorId: 1,
                  title: "建设用地减量化",
                  type: 1,
                  content: "建设用地减量化",
                  parentId: 16,
                  modelName: "zhj_jsydjlh_tb_layer",
                  createTime: 1672302349164,
                  authorName: "super_user",
                  id: 51,
                  state: 0,
                  tag: "zhj_jsydjlh",
                },
                {
                  level: 0,
                  modelId: 54,
                  updateTime: 1672299627728,
                  authorId: 1,
                  title: "永久基本农田",
                  type: 1,
                  content: "永久基本农田",
                  parentId: 16,
                  modelName: "zjz_tudi_yjjbnt_tb_layer",
                  createTime: 1672299627728,
                  authorName: "super_user",
                  id: 50,
                  state: 0,
                  tag: "zjz_tudi_yjjbnt",
                },
                {
                  level: 0,
                  modelId: 49,
                  updateTime: 1672296432695,
                  authorId: 1,
                  title: "一般耕地",
                  type: 1,
                  content: "一般耕地",
                  parentId: 16,
                  modelName: "zjz_tudi_yiban_tb_layer",
                  createTime: 1672296432695,
                  authorName: "super_user",
                  id: 47,
                  state: 0,
                  tag: "zjz_tudi_yiban",
                },
              ],
              updateTime: 1672215002786,
              authorId: 4,
              title: "土地资源",
              type: 0,
              content: "土地资源",
              parentId: 14,
              createTime: 1672215002786,
              authorName: "user001",
              id: 16,
              state: 0,
              tag: "tudi",
            },
          ],
          updateTime: 1672214943299,
          authorId: 1,
          title: "张江镇",
          type: 0,
          content: "张江镇",
          parentId: 13,
          createTime: 1672214943299,
          authorName: "super_user",
          id: 14,
          state: 0,
          tag: "zhangjiangzhen",
        },
      ],
      updateTime: 1672214914948,
      authorId: 1,
      title: "所有图层",
      type: 0,
      content: "所有图层",
      parentId: -1,
      createTime: 1672214914948,
      authorName: "super_user",
      id: 13,
      state: 0,
      tag: "test_cc",
    },
    {
      level: 0,
      columnList: [
        {
          level: 0,
          modelId: 51,
          updateTime: 1672297720750,
          authorId: 1,
          title: "我的任务",
          type: 1,
          content: "审计局专用",
          parentId: 12,
          modelName: "task_my_task",
          createTime: 1672297720750,
          authorName: "super_user",
          id: 48,
          state: 0,
          tag: "task",
        },
        {
          level: 0,
          modelId: 33,
          updateTime: 1672221225397,
          authorId: 4,
          title: "地图底图服务",
          type: 1,
          content: "地图底图服务",
          parentId: 12,
          modelName: "c_image_basemap",
          createTime: 1672221225397,
          authorName: "user001",
          id: 35,
          state: 0,
          tag: "c_image",
        },
        {
          level: 0,
          modelId: 31,
          updateTime: 1672221074934,
          authorId: 4,
          title: "系统信息",
          type: 1,
          content: "系统信息",
          parentId: 12,
          modelName: "system_system_info",
          createTime: 1672221074934,
          authorName: "user001",
          id: 33,
          state: 0,
          tag: "system",
        },
        {
          level: 0,
          modelId: 29,
          updateTime: 1672220942346,
          authorId: 4,
          title: "资金投入_街道",
          type: 1,
          content: "资金投入_街道",
          parentId: 12,
          modelName: "investment_investment",
          createTime: 1672220942346,
          authorName: "user001",
          id: 31,
          state: 0,
          tag: "investment",
        },
        {
          level: 0,
          modelId: 28,
          updateTime: 1672220844675,
          authorId: 4,
          title: "街镇资源分类",
          type: 1,
          content: "街镇资源分类",
          parentId: 12,
          modelName: "jzzyfl_down_sources",
          createTime: 1672220844675,
          authorName: "user001",
          id: 30,
          state: 0,
          tag: "jzzyfl",
        },
        {
          level: 0,
          modelId: 27,
          updateTime: 1672220736415,
          authorId: 4,
          title: "全流程管理",
          type: 1,
          content: "全流程管理",
          parentId: 12,
          modelName: "project_qlcgl_sh",
          createTime: 1672220736415,
          authorName: "user001",
          id: 29,
          state: 0,
          tag: "project",
        },
        {
          level: 0,
          modelId: 16,
          updateTime: 1672218612379,
          authorId: 4,
          title: "频发问题",
          type: 1,
          content: "频发问题",
          parentId: 12,
          modelName: "pfwt_pfwt_sh",
          createTime: 1672218612379,
          authorName: "user001",
          id: 24,
          state: 0,
          tag: "pfwt",
        },
        {
          level: 0,
          modelId: 15,
          updateTime: 1672218073882,
          authorId: 4,
          title: "法律法规",
          type: 1,
          content: "法律法规",
          parentId: 12,
          modelName: "flfg_flfg_sh",
          createTime: 1672218073882,
          authorName: "user001",
          id: 23,
          state: 0,
          tag: "flfg",
        },
      ],
      updateTime: 1672214895836,
      authorId: 1,
      title: "浦东审计",
      type: 0,
      content: "浦东审计",
      parentId: -1,
      createTime: 1672214895836,
      authorName: "super_user",
      id: 12,
      state: 0,
      tag: "puDong_audit",
    },
  ],
};

let data = res.content.map((item1) => {
  if (item1.title === "所有图层" && item1.columnList.length > 0) {
    return {
      id: `${item1.title}_${item1.id}`,
      label: item1.title,
      children: [],
    };
  }
});
let modelData = [];
data.forEach((v) => {
  if (v) {
    modelData.unshift(v);
  }
});

console.log(modelData);
